---
version: '3'
services:
  # plex media server
#  plex:
#    image: linuxserver/plex
#    container_name: plex
#    hostname: plex
#    restart: always
#    network_mode: host
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - VERSION=latest
#   volumes:
#     - $base/plex/config:/config
#     - $base/plex/transcode:/transcode
#     - $media:/data
  # media-vpn container (openvpn)
  # ports: hydra=5075 lazylibrarian=5299 radarr=7878 deluge=8112 lidarr=8686 sonarr=8989 jackett=9117
  media-vpn:
    image: openvpn
    container_name: media-vpn
    hostname: media-vpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    ports:
      - "5060:5060"
      - "5075:5075"
      - "5299:5299"
      - "7878:7878"
      - "8112:8112"
      - "8686:8686"
      - "8989:8989"
      - "9117:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - FORCEVPN=true
    volumes:
      - ${base}/media-vpn/config:/config
  # mariadb container for kodi db
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=a707b45
    network_mode: bridge
    ports:
      - "3306:3306"
    volumes:
      - $base/mariadb/config:/config
  # usenet client
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    hostname: nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: bridge
    ports:
      - "6789:6789"
    volumes:
      - ${base}/nzbget/config:/config
      - ${dl}:/downloads
      - ${media}:/media
  # bittorrent client
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    restart: always
    network_mode: service:media-vpn
    depends_on:
      - media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/deluge/config:/config
      - ${dl}:/downloads
  # nzb indexer
  hydra:
    image: linuxserver/hydra
    container_name: hydra
    restart: always
    depends_on:
      - media-vpn
      - nzbget
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/hydra/config:/config
  # bittorrent search aggregator
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    depends_on:
      - media-vpn
      - nzbget
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro
  # ebook watcher/downloader
  lazylibrarian:
    image: thraxis/lazylibrarian-calibre
    container_name: lazylibrarian
    restart: always
    depends_on:
      - deluge
      - hydra
      - jackett
      - media-vpn
      - nzbget
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/lazylibrarian/config:/config
      - ${dl}/completed:/downloads
      - ${media}/ebooks:/books
  # music watcher/grabber
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: always
    depends_on:
      - deluge
      - hydra
      - jackett
      - media-vpn
      - nzbget
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/lidarr/config:/config
      - ${dl}:/downloads
      - ${media}:/media
      - ${media}/music:/music
  # movie watcher/grabber
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    depends_on:
      - deluge
      - hydra
      - jackett
      - media-vpn
      - nzbget
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/radarr/config:/config
      - ${dl}:/downloads
      - ${media}:/media
      - ${media}/video/Movies:/movies
  # tv show watcher/grabber
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    depends_on:
      - deluge
      - hydra
      - jackett
      - media-vpn
      - nzbget
    network_mode: service:media-vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${base}/sonarr/config:/config
      - ${dl}:/downloads
      - ${media}:/media
      - ${media}/video/TV Shows:/tv
  # web UI combining all services into single interface
  muximux:
    image: linuxserver/muximux
    container_name: muximux
    hostname: muximux
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: bridge
    ports:
      - "8081:80"
    volumes:
      - ${base}/muximux/config:/config
  # syncthing file sync agent
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - $base/syncthing/config:/config
      - $sync:/data
  unifi:
    image: linuxserver/unifi:latest
    container_name: unifi
    hostname: unifi
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: bridge
    ports:
      - "3478:3478/udp"
      - "8090:8080"
      - "8091:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "10001:10001/udp"
    volumes:
      - $base/unifi/config:/config
